artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AshenLanarolle/Datasets/raw/main/Redwine.zip
  local_data_file: artifacts/data_ingestion/Redwine.zip
  unzip_dir: artifacts/data_ingestion